### ISSUE TITLE
feat: Include column name in failed ser/de attempt

### ISSUE THREAD

**Issue by jalcine** [twistedfall/serde_rusqlite#19]
Currently, on any deserialization failure, I have to peek into each column to see which value might be incorrect. I'm curious if the Error type could be expanded to include either the column index or the name of the column being deserialized to aid in the debugging process.

(Originally published at: https://jacky.wtf/2023/2/R-Tq)

**Comment by twistedfall** [comment]
Hi, sorry for neglecting it for so long, but I've just released version 0.33 with this feature. The `Deserialization` variant of the `Error` now contains 2 fields: optional `column` that indicates a failing db column when it's applicable and `message`, the error message from `serde`

**Comment by jalcine** [comment]
Please don't apologize: you've written code and shared it for free on the Web. You owe me nothing, and I appreciate you still spending time to maintain this project. Thanks, this'll make apps easier to debug.

(Originally published at: https://jacky.wtf/2023/5/PKUP)
