### ISSUE TITLE
 Request for License Conversion to MIT or Apache 2.0

### ISSUE THREAD

**Issue by antimora** [twistedfall/serde_rusqlite#21]
This ticket is to request a change in the current project license to either the MIT License or the Apache License 2.0. There are useful parts for serialization that we would like to copy to our project but license is not compatible with [Burn's project](https://github.com/burn-rs/burn).

**Comment by twistedfall** [comment]
Can you please provide more details about your reasoning? You can link to LGPL-3 licensed libraries in an Apache or MIT licensed project as far as I know.

**Comment by antimora** [comment]
@twistedfall, I appreciate the work you've put into your library and we're currently linking it as you've suggested. However, I initially wanted to heavily modify and incorporate parts of your code (while maintaining proper attribution) into our project, but the LGPL-3 license is more restrictive than the ones we're using (Apache 2 or MIT).

Since I raised this issue, I've come across a workaround for some parts of the problem. If it's acceptable to you, I might propose a PR for these changes.

To elaborate, our goal is to serialize complex data fields into byte format, potentially using bincode or message pack. We prefer handling this at the serializer level as the struct requiring serialization is user-provided.

**Comment by twistedfall** [comment]
Thanks for the explanation! I'm really looking forward to that PR!

**Comment by antimora** [comment]
@twistedfall I went for another solution without making changes to your code. We still use your library however. 

The licensing issue came up once again. This time one of our users of Burn [brought up a potential issue](https://github.com/burn-rs/burn/issues/719). 

If it's possible for you and you are okay with this, could we convert serde_rustqlite's license to MIT/Apache2?

**Comment by antimora** [comment]
Here is our reasoning for this request written by @dae 


> You're no doubt already aware of this, but just stating it for the benefit of other onlookers: while static linking is not an issue for Burn itself, it can be a problem for apps that include Burn in them. As I understand it, the LGPL requires that a distributed program allow replacing any included LGPL code with a modified version. In other languages where the LGPL code is in a dynamic library, users can just drop in a replacement dll, but with Rust and static linking, that typically means you need to provide your entire program's source code so that the user can recompile it. It may be possible to compile the other parts of the app into one or more rlibs and distribute those so that the user can do the final build step, but I'm not sure how practical that would actually be, and I suspect any apps that can't distribute their source code would just avoid LGPL dependencies instead.
