### ISSUE TITLE
serde_json::Value from string

### ISSUE THREAD

**Issue by jeprojects** [twistedfall/serde_rusqlite#6]
I am doing this to grab the rusqlite db rows into a struct:

pub struct Blog {
    pub blog_id: Option<u32>,
    pub data: serde_json::Value,
}

`let rows = from_rows::<Blog>(stmt.query(NO_PARAMS)?).flatten().collect();`

The `data` field is a json string in rusqlite, but when using `from_rows` it will convert it into a serde_json::Value but of the wrong type. It converts its to a pure string value which then the keys can not be accessed:

```
    /// Represents a JSON string.
    ///
    /// ```edition2018
    /// # use serde_json::json;
    /// #
    /// let v = json!("a string");
    /// ```
    String(String),
```

Any way around this?

**Comment by twistedfall** [comment]
Well, related to #4, SQLite can't store anything other than [primitive types](https://www.sqlite.org/datatype3.html#storage_classes_and_datatypes). So you'll need to do some preprocessing on that. If you want it to happen transparently you might want to employ [`deserialize_with`](https://serde.rs/field-attrs.html#deserialize_with) serde attribute and its friends.
